const sampleMovies = [
  {
    _id: 1,
    owner: 11,
    nameRU: '33 слова о дизайне',
    nameEN: 'Film',
    description: 'Описание',
    thumbnail: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/92/35_movie_film.jpg/600px-35_movie_film.jpg',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/92/35_movie_film.jpg/600px-35_movie_film.jpg',
    trailerlink: 'https://youtu.be/dQw4w9WgXcQ?t=43',
    year: '2023',
    country: 'Россия',
    director: 'Валентина Краснова',
    duration: '3 ч. 17 мин.',
  },
  {
    _id: 2,
    owner: 11,
    nameRU: '33 слова о дизайне',
    nameEN: 'Film',
    description: 'Описание',
    thumbnail: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/92/35_movie_film.jpg/600px-35_movie_film.jpg',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/92/35_movie_film.jpg/600px-35_movie_film.jpg',
    trailerlink: 'https://youtu.be/dQw4w9WgXcQ?t=43',
    year: '2023',
    country: 'Россия',
    director: 'Валентина Краснова',
    duration: '3 ч. 17 мин.',
  },
  {
    _id: 3,
    owner: 11,
    nameRU: '33 слова о дизайне',
    nameEN: 'Film',
    description: 'Описание',
    thumbnail: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/92/35_movie_film.jpg/600px-35_movie_film.jpg',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/92/35_movie_film.jpg/600px-35_movie_film.jpg',
    trailerlink: 'https://youtu.be/dQw4w9WgXcQ?t=43',
    year: '2023',
    country: 'Россия',
    director: 'Валентина Краснова',
    duration: '3 ч. 17 мин.',
  },
  {
    _id: 4,
    owner: 11,
    nameRU: '33 слова о дизайне',
    nameEN: 'Film',
    description: 'Описание',
    thumbnail: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/92/35_movie_film.jpg/600px-35_movie_film.jpg',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/92/35_movie_film.jpg/600px-35_movie_film.jpg',
    trailerlink: 'https://youtu.be/dQw4w9WgXcQ?t=43',
    year: '2023',
    country: 'Россия',
    director: 'Валентина Краснова',
    duration: '3 ч. 17 мин.',
  },
  {
    _id: 5,
    owner: 11,
    nameRU: '33 слова о дизайне',
    nameEN: 'Film',
    description: 'Описание',
    thumbnail: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/92/35_movie_film.jpg/600px-35_movie_film.jpg',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/92/35_movie_film.jpg/600px-35_movie_film.jpg',
    trailerlink: 'https://youtu.be/dQw4w9WgXcQ?t=43',
    year: '2023',
    country: 'Россия',
    director: 'Валентина Краснова',
    duration: '3 ч. 17 мин.',
  },
  {
    _id: 6,
    owner: 11,
    nameRU: '33 слова о дизайне',
    nameEN: 'Film',
    description: 'Описание',
    thumbnail: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/92/35_movie_film.jpg/600px-35_movie_film.jpg',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/92/35_movie_film.jpg/600px-35_movie_film.jpg',
    trailerlink: 'https://youtu.be/dQw4w9WgXcQ?t=43',
    year: '2023',
    country: 'Россия',
    director: 'Валентина Краснова',
    duration: '3 ч. 17 мин.',
  },
  {
    _id: 7,
    owner: 11,
    nameRU: '33 слова о дизайне',
    nameEN: 'Film',
    description: 'Описание',
    thumbnail: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/92/35_movie_film.jpg/600px-35_movie_film.jpg',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/92/35_movie_film.jpg/600px-35_movie_film.jpg',
    trailerlink: 'https://youtu.be/dQw4w9WgXcQ?t=43',
    year: '2023',
    country: 'Россия',
    director: 'Валентина Краснова',
    duration: '3 ч. 17 мин.',
  },
  {
    _id: 8,
    owner: 11,
    nameRU: '33 слова о дизайне',
    nameEN: 'Film',
    description: 'Описание',
    thumbnail: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/92/35_movie_film.jpg/600px-35_movie_film.jpg',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/92/35_movie_film.jpg/600px-35_movie_film.jpg',
    trailerlink: 'https://youtu.be/dQw4w9WgXcQ?t=43',
    year: '2023',
    country: 'Россия',
    director: 'Валентина Краснова',
    duration: '3 ч. 17 мин.',
  },
  {
    _id: 9,
    owner: 11,
    nameRU: '33 слова о дизайне',
    nameEN: 'Film',
    description: 'Описание',
    thumbnail: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/92/35_movie_film.jpg/600px-35_movie_film.jpg',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/92/35_movie_film.jpg/600px-35_movie_film.jpg',
    trailerlink: 'https://youtu.be/dQw4w9WgXcQ?t=43',
    year: '2023',
    country: 'Россия',
    director: 'Валентина Краснова',
    duration: '3 ч. 17 мин.',
  },
  {
    _id: 10,
    owner: 11,
    nameRU: '33 слова о дизайне',
    nameEN: 'Film',
    description: 'Описание',
    thumbnail: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/92/35_movie_film.jpg/600px-35_movie_film.jpg',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/92/35_movie_film.jpg/600px-35_movie_film.jpg',
    trailerlink: 'https://youtu.be/dQw4w9WgXcQ?t=43',
    year: '2023',
    country: 'Россия',
    director: 'Валентина Краснова',
    duration: '3 ч. 17 мин.',
  },
  {
    _id: 11,
    owner: 11,
    nameRU: '33 слова о дизайне',
    nameEN: 'Film',
    description: 'Описание',
    thumbnail: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/92/35_movie_film.jpg/600px-35_movie_film.jpg',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/92/35_movie_film.jpg/600px-35_movie_film.jpg',
    trailerlink: 'https://youtu.be/dQw4w9WgXcQ?t=43',
    year: '2023',
    country: 'Россия',
    director: 'Валентина Краснова',
    duration: '3 ч. 17 мин.',
  },
  {
    _id: 12,
    owner: 11,
    nameRU: '33 слова о дизайне',
    nameEN: 'Film',
    description: 'Описание',
    thumbnail: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/92/35_movie_film.jpg/600px-35_movie_film.jpg',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/92/35_movie_film.jpg/600px-35_movie_film.jpg',
    trailerlink: 'https://youtu.be/dQw4w9WgXcQ?t=43',
    year: '2023',
    country: 'Россия',
    director: 'Валентина Краснова',
    duration: '3 ч. 17 мин.',
  },
  {
    _id: 13,
    owner: 11,
    nameRU: '33 слова о дизайне',
    nameEN: 'Film',
    description: 'Описание',
    thumbnail: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/92/35_movie_film.jpg/600px-35_movie_film.jpg',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/92/35_movie_film.jpg/600px-35_movie_film.jpg',
    trailerlink: 'https://youtu.be/dQw4w9WgXcQ?t=43',
    year: '2023',
    country: 'Россия',
    director: 'Валентина Краснова',
    duration: '3 ч. 17 мин.',
  },
  {
    _id: 14,
    owner: 11,
    nameRU: '33 слова о дизайне',
    nameEN: 'Film',
    description: 'Описание',
    thumbnail: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/92/35_movie_film.jpg/600px-35_movie_film.jpg',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/92/35_movie_film.jpg/600px-35_movie_film.jpg',
    trailerlink: 'https://youtu.be/dQw4w9WgXcQ?t=43',
    year: '2023',
    country: 'Россия',
    director: 'Валентина Краснова',
    duration: '3 ч. 17 мин.',
  },
  {
    _id: 15,
    owner: 11,
    nameRU: '33 слова о дизайне',
    nameEN: 'Film',
    description: 'Описание',
    thumbnail: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/92/35_movie_film.jpg/600px-35_movie_film.jpg',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/92/35_movie_film.jpg/600px-35_movie_film.jpg',
    trailerlink: 'https://youtu.be/dQw4w9WgXcQ?t=43',
    year: '2023',
    country: 'Россия',
    director: 'Валентина Краснова',
    duration: '3 ч. 17 мин.',
  },
  {
    _id: 16,
    owner: 11,
    nameRU: '33 слова о дизайне',
    nameEN: 'Film',
    description: 'Описание',
    thumbnail: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/92/35_movie_film.jpg/600px-35_movie_film.jpg',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/92/35_movie_film.jpg/600px-35_movie_film.jpg',
    trailerlink: 'https://youtu.be/dQw4w9WgXcQ?t=43',
    year: '2023',
    country: 'Россия',
    director: 'Валентина Краснова',
    duration: '3 ч. 17 мин.',
  },
];

export default sampleMovies;